/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthCreateOrgIndexRouteImport } from './routes/auth/create-org/index'
import { Route as AdminInventoryReceiveRouteImport } from './routes/_admin/inventory/receive'
import { Route as AdminCatalogProductsIndexRouteImport } from './routes/_admin/catalog/products/index'
import { Route as AdminCatalogProductsNewRouteImport } from './routes/_admin/catalog/products/new'
import { Route as AdminCatalogProductsProductIdRouteImport } from './routes/_admin/catalog/products/$productId'
import { Route as AuthSignInTasksChooseOrganizationIndexRouteImport } from './routes/auth/sign-in/tasks/choose-organization/index'
import { Route as AdminInventoryVariantsVariantIdStockRouteImport } from './routes/_admin/inventory/variants/$variantId.stock'
import { Route as AdminCatalogProductsProductIdVariantsNewRouteImport } from './routes/_admin/catalog/products/$productId.variants.new'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateOrgIndexRoute = AuthCreateOrgIndexRouteImport.update({
  id: '/create-org/',
  path: '/create-org/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AdminInventoryReceiveRoute = AdminInventoryReceiveRouteImport.update({
  id: '/inventory/receive',
  path: '/inventory/receive',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogProductsIndexRoute =
  AdminCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogProductsNewRoute = AdminCatalogProductsNewRouteImport.update({
  id: '/catalog/products/new',
  path: '/catalog/products/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogProductsProductIdRoute =
  AdminCatalogProductsProductIdRouteImport.update({
    id: '/catalog/products/$productId',
    path: '/catalog/products/$productId',
    getParentRoute: () => AdminRoute,
  } as any)
const AuthSignInTasksChooseOrganizationIndexRoute =
  AuthSignInTasksChooseOrganizationIndexRouteImport.update({
    id: '/sign-in/tasks/choose-organization/',
    path: '/sign-in/tasks/choose-organization/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AdminInventoryVariantsVariantIdStockRoute =
  AdminInventoryVariantsVariantIdStockRouteImport.update({
    id: '/inventory/variants/$variantId/stock',
    path: '/inventory/variants/$variantId/stock',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogProductsProductIdVariantsNewRoute =
  AdminCatalogProductsProductIdVariantsNewRouteImport.update({
    id: '/variants/new',
    path: '/variants/new',
    getParentRoute: () => AdminCatalogProductsProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/': typeof AdminIndexRoute
  '/inventory/receive': typeof AdminInventoryReceiveRoute
  '/auth/create-org': typeof AuthCreateOrgIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/catalog/products/$productId': typeof AdminCatalogProductsProductIdRouteWithChildren
  '/catalog/products/new': typeof AdminCatalogProductsNewRoute
  '/catalog/products': typeof AdminCatalogProductsIndexRoute
  '/inventory/variants/$variantId/stock': typeof AdminInventoryVariantsVariantIdStockRoute
  '/auth/sign-in/tasks/choose-organization': typeof AuthSignInTasksChooseOrganizationIndexRoute
  '/catalog/products/$productId/variants/new': typeof AdminCatalogProductsProductIdVariantsNewRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/': typeof AdminIndexRoute
  '/inventory/receive': typeof AdminInventoryReceiveRoute
  '/auth/create-org': typeof AuthCreateOrgIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/catalog/products/$productId': typeof AdminCatalogProductsProductIdRouteWithChildren
  '/catalog/products/new': typeof AdminCatalogProductsNewRoute
  '/catalog/products': typeof AdminCatalogProductsIndexRoute
  '/inventory/variants/$variantId/stock': typeof AdminInventoryVariantsVariantIdStockRoute
  '/auth/sign-in/tasks/choose-organization': typeof AuthSignInTasksChooseOrganizationIndexRoute
  '/catalog/products/$productId/variants/new': typeof AdminCatalogProductsProductIdVariantsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/inventory/receive': typeof AdminInventoryReceiveRoute
  '/auth/create-org/': typeof AuthCreateOrgIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/_admin/catalog/products/$productId': typeof AdminCatalogProductsProductIdRouteWithChildren
  '/_admin/catalog/products/new': typeof AdminCatalogProductsNewRoute
  '/_admin/catalog/products/': typeof AdminCatalogProductsIndexRoute
  '/_admin/inventory/variants/$variantId/stock': typeof AdminInventoryVariantsVariantIdStockRoute
  '/auth/sign-in/tasks/choose-organization/': typeof AuthSignInTasksChooseOrganizationIndexRoute
  '/_admin/catalog/products/$productId/variants/new': typeof AdminCatalogProductsProductIdVariantsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/settings'
    | '/'
    | '/inventory/receive'
    | '/auth/create-org'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/catalog/products/$productId'
    | '/catalog/products/new'
    | '/catalog/products'
    | '/inventory/variants/$variantId/stock'
    | '/auth/sign-in/tasks/choose-organization'
    | '/catalog/products/$productId/variants/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/settings'
    | '/'
    | '/inventory/receive'
    | '/auth/create-org'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/catalog/products/$productId'
    | '/catalog/products/new'
    | '/catalog/products'
    | '/inventory/variants/$variantId/stock'
    | '/auth/sign-in/tasks/choose-organization'
    | '/catalog/products/$productId/variants/new'
  id:
    | '__root__'
    | '/auth'
    | '/_admin'
    | '/_admin/settings'
    | '/_admin/'
    | '/_admin/inventory/receive'
    | '/auth/create-org/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/_admin/catalog/products/$productId'
    | '/_admin/catalog/products/new'
    | '/_admin/catalog/products/'
    | '/_admin/inventory/variants/$variantId/stock'
    | '/auth/sign-in/tasks/choose-organization/'
    | '/_admin/catalog/products/$productId/variants/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/create-org/': {
      id: '/auth/create-org/'
      path: '/create-org'
      fullPath: '/auth/create-org'
      preLoaderRoute: typeof AuthCreateOrgIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/inventory/receive': {
      id: '/_admin/inventory/receive'
      path: '/inventory/receive'
      fullPath: '/inventory/receive'
      preLoaderRoute: typeof AdminInventoryReceiveRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/products/': {
      id: '/_admin/catalog/products/'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof AdminCatalogProductsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/products/new': {
      id: '/_admin/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/catalog/products/new'
      preLoaderRoute: typeof AdminCatalogProductsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/products/$productId': {
      id: '/_admin/catalog/products/$productId'
      path: '/catalog/products/$productId'
      fullPath: '/catalog/products/$productId'
      preLoaderRoute: typeof AdminCatalogProductsProductIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth/sign-in/tasks/choose-organization/': {
      id: '/auth/sign-in/tasks/choose-organization/'
      path: '/sign-in/tasks/choose-organization'
      fullPath: '/auth/sign-in/tasks/choose-organization'
      preLoaderRoute: typeof AuthSignInTasksChooseOrganizationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_admin/inventory/variants/$variantId/stock': {
      id: '/_admin/inventory/variants/$variantId/stock'
      path: '/inventory/variants/$variantId/stock'
      fullPath: '/inventory/variants/$variantId/stock'
      preLoaderRoute: typeof AdminInventoryVariantsVariantIdStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/products/$productId/variants/new': {
      id: '/_admin/catalog/products/$productId/variants/new'
      path: '/variants/new'
      fullPath: '/catalog/products/$productId/variants/new'
      preLoaderRoute: typeof AdminCatalogProductsProductIdVariantsNewRouteImport
      parentRoute: typeof AdminCatalogProductsProductIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCreateOrgIndexRoute: typeof AuthCreateOrgIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthSignInTasksChooseOrganizationIndexRoute: typeof AuthSignInTasksChooseOrganizationIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCreateOrgIndexRoute: AuthCreateOrgIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthSignInTasksChooseOrganizationIndexRoute:
    AuthSignInTasksChooseOrganizationIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface AdminCatalogProductsProductIdRouteChildren {
  AdminCatalogProductsProductIdVariantsNewRoute: typeof AdminCatalogProductsProductIdVariantsNewRoute
}

const AdminCatalogProductsProductIdRouteChildren: AdminCatalogProductsProductIdRouteChildren =
  {
    AdminCatalogProductsProductIdVariantsNewRoute:
      AdminCatalogProductsProductIdVariantsNewRoute,
  }

const AdminCatalogProductsProductIdRouteWithChildren =
  AdminCatalogProductsProductIdRoute._addFileChildren(
    AdminCatalogProductsProductIdRouteChildren,
  )

interface AdminRouteChildren {
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminInventoryReceiveRoute: typeof AdminInventoryReceiveRoute
  AdminCatalogProductsProductIdRoute: typeof AdminCatalogProductsProductIdRouteWithChildren
  AdminCatalogProductsNewRoute: typeof AdminCatalogProductsNewRoute
  AdminCatalogProductsIndexRoute: typeof AdminCatalogProductsIndexRoute
  AdminInventoryVariantsVariantIdStockRoute: typeof AdminInventoryVariantsVariantIdStockRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminInventoryReceiveRoute: AdminInventoryReceiveRoute,
  AdminCatalogProductsProductIdRoute:
    AdminCatalogProductsProductIdRouteWithChildren,
  AdminCatalogProductsNewRoute: AdminCatalogProductsNewRoute,
  AdminCatalogProductsIndexRoute: AdminCatalogProductsIndexRoute,
  AdminInventoryVariantsVariantIdStockRoute:
    AdminInventoryVariantsVariantIdStockRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
