/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardCatalogIndexRouteImport } from './routes/dashboard/catalog/index'
import { Route as AuthSignUpIndexRouteImport } from './routes/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './routes/auth/sign-in/index'
import { Route as AuthCreateOrgIndexRouteImport } from './routes/auth/create-org/index'
import { Route as DashboardInventoryReceiveRouteImport } from './routes/dashboard/inventory/receive'
import { Route as DashboardCatalogProductsIndexRouteImport } from './routes/dashboard/catalog/products/index'
import { Route as DashboardCatalogProductsNewRouteImport } from './routes/dashboard/catalog/products/new'
import { Route as DashboardCatalogProductsProductIdRouteImport } from './routes/dashboard/catalog/products/$productId'
import { Route as AuthSignInTasksChooseOrganizationIndexRouteImport } from './routes/auth/sign-in/tasks/choose-organization/index'
import { Route as DashboardInventoryVariantsVariantIdStockRouteImport } from './routes/dashboard/inventory/variants/$variantId/stock'
import { Route as DashboardCatalogProductsProductIdVariantsNewRouteImport } from './routes/dashboard/catalog/products/$productId/variants/new'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCatalogIndexRoute = DashboardCatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthCreateOrgIndexRoute = AuthCreateOrgIndexRouteImport.update({
  id: '/create-org/',
  path: '/create-org/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DashboardInventoryReceiveRoute =
  DashboardInventoryReceiveRouteImport.update({
    id: '/inventory/receive',
    path: '/inventory/receive',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogProductsIndexRoute =
  DashboardCatalogProductsIndexRouteImport.update({
    id: '/catalog/products/',
    path: '/catalog/products/',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogProductsNewRoute =
  DashboardCatalogProductsNewRouteImport.update({
    id: '/catalog/products/new',
    path: '/catalog/products/new',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogProductsProductIdRoute =
  DashboardCatalogProductsProductIdRouteImport.update({
    id: '/catalog/products/$productId',
    path: '/catalog/products/$productId',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const AuthSignInTasksChooseOrganizationIndexRoute =
  AuthSignInTasksChooseOrganizationIndexRouteImport.update({
    id: '/sign-in/tasks/choose-organization/',
    path: '/sign-in/tasks/choose-organization/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const DashboardInventoryVariantsVariantIdStockRoute =
  DashboardInventoryVariantsVariantIdStockRouteImport.update({
    id: '/inventory/variants/$variantId/stock',
    path: '/inventory/variants/$variantId/stock',
    getParentRoute: () => DashboardRouteRoute,
  } as any)
const DashboardCatalogProductsProductIdVariantsNewRoute =
  DashboardCatalogProductsProductIdVariantsNewRouteImport.update({
    id: '/variants/new',
    path: '/variants/new',
    getParentRoute: () => DashboardCatalogProductsProductIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/inventory/receive': typeof DashboardInventoryReceiveRoute
  '/auth/create-org': typeof AuthCreateOrgIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/dashboard/catalog': typeof DashboardCatalogIndexRoute
  '/dashboard/catalog/products/$productId': typeof DashboardCatalogProductsProductIdRouteWithChildren
  '/dashboard/catalog/products/new': typeof DashboardCatalogProductsNewRoute
  '/dashboard/catalog/products': typeof DashboardCatalogProductsIndexRoute
  '/dashboard/inventory/variants/$variantId/stock': typeof DashboardInventoryVariantsVariantIdStockRoute
  '/auth/sign-in/tasks/choose-organization': typeof AuthSignInTasksChooseOrganizationIndexRoute
  '/dashboard/catalog/products/$productId/variants/new': typeof DashboardCatalogProductsProductIdVariantsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/inventory/receive': typeof DashboardInventoryReceiveRoute
  '/auth/create-org': typeof AuthCreateOrgIndexRoute
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/dashboard/catalog': typeof DashboardCatalogIndexRoute
  '/dashboard/catalog/products/$productId': typeof DashboardCatalogProductsProductIdRouteWithChildren
  '/dashboard/catalog/products/new': typeof DashboardCatalogProductsNewRoute
  '/dashboard/catalog/products': typeof DashboardCatalogProductsIndexRoute
  '/dashboard/inventory/variants/$variantId/stock': typeof DashboardInventoryVariantsVariantIdStockRoute
  '/auth/sign-in/tasks/choose-organization': typeof AuthSignInTasksChooseOrganizationIndexRoute
  '/dashboard/catalog/products/$productId/variants/new': typeof DashboardCatalogProductsProductIdVariantsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/inventory/receive': typeof DashboardInventoryReceiveRoute
  '/auth/create-org/': typeof AuthCreateOrgIndexRoute
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/dashboard/catalog/': typeof DashboardCatalogIndexRoute
  '/dashboard/catalog/products/$productId': typeof DashboardCatalogProductsProductIdRouteWithChildren
  '/dashboard/catalog/products/new': typeof DashboardCatalogProductsNewRoute
  '/dashboard/catalog/products/': typeof DashboardCatalogProductsIndexRoute
  '/dashboard/inventory/variants/$variantId/stock': typeof DashboardInventoryVariantsVariantIdStockRoute
  '/auth/sign-in/tasks/choose-organization/': typeof AuthSignInTasksChooseOrganizationIndexRoute
  '/dashboard/catalog/products/$productId/variants/new': typeof DashboardCatalogProductsProductIdVariantsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/inventory/receive'
    | '/auth/create-org'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/catalog'
    | '/dashboard/catalog/products/$productId'
    | '/dashboard/catalog/products/new'
    | '/dashboard/catalog/products'
    | '/dashboard/inventory/variants/$variantId/stock'
    | '/auth/sign-in/tasks/choose-organization'
    | '/dashboard/catalog/products/$productId/variants/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard/settings'
    | '/dashboard'
    | '/dashboard/inventory/receive'
    | '/auth/create-org'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/catalog'
    | '/dashboard/catalog/products/$productId'
    | '/dashboard/catalog/products/new'
    | '/dashboard/catalog/products'
    | '/dashboard/inventory/variants/$variantId/stock'
    | '/auth/sign-in/tasks/choose-organization'
    | '/dashboard/catalog/products/$productId/variants/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/settings'
    | '/dashboard/'
    | '/dashboard/inventory/receive'
    | '/auth/create-org/'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/dashboard/catalog/'
    | '/dashboard/catalog/products/$productId'
    | '/dashboard/catalog/products/new'
    | '/dashboard/catalog/products/'
    | '/dashboard/inventory/variants/$variantId/stock'
    | '/auth/sign-in/tasks/choose-organization/'
    | '/dashboard/catalog/products/$productId/variants/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/': {
      id: '/dashboard/catalog/'
      path: '/catalog'
      fullPath: '/dashboard/catalog'
      preLoaderRoute: typeof DashboardCatalogIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/create-org/': {
      id: '/auth/create-org/'
      path: '/create-org'
      fullPath: '/auth/create-org'
      preLoaderRoute: typeof AuthCreateOrgIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/inventory/receive': {
      id: '/dashboard/inventory/receive'
      path: '/inventory/receive'
      fullPath: '/dashboard/inventory/receive'
      preLoaderRoute: typeof DashboardInventoryReceiveRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/products/': {
      id: '/dashboard/catalog/products/'
      path: '/catalog/products'
      fullPath: '/dashboard/catalog/products'
      preLoaderRoute: typeof DashboardCatalogProductsIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/products/new': {
      id: '/dashboard/catalog/products/new'
      path: '/catalog/products/new'
      fullPath: '/dashboard/catalog/products/new'
      preLoaderRoute: typeof DashboardCatalogProductsNewRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/products/$productId': {
      id: '/dashboard/catalog/products/$productId'
      path: '/catalog/products/$productId'
      fullPath: '/dashboard/catalog/products/$productId'
      preLoaderRoute: typeof DashboardCatalogProductsProductIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/auth/sign-in/tasks/choose-organization/': {
      id: '/auth/sign-in/tasks/choose-organization/'
      path: '/sign-in/tasks/choose-organization'
      fullPath: '/auth/sign-in/tasks/choose-organization'
      preLoaderRoute: typeof AuthSignInTasksChooseOrganizationIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/dashboard/inventory/variants/$variantId/stock': {
      id: '/dashboard/inventory/variants/$variantId/stock'
      path: '/inventory/variants/$variantId/stock'
      fullPath: '/dashboard/inventory/variants/$variantId/stock'
      preLoaderRoute: typeof DashboardInventoryVariantsVariantIdStockRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/catalog/products/$productId/variants/new': {
      id: '/dashboard/catalog/products/$productId/variants/new'
      path: '/variants/new'
      fullPath: '/dashboard/catalog/products/$productId/variants/new'
      preLoaderRoute: typeof DashboardCatalogProductsProductIdVariantsNewRouteImport
      parentRoute: typeof DashboardCatalogProductsProductIdRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthCreateOrgIndexRoute: typeof AuthCreateOrgIndexRoute
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
  AuthSignInTasksChooseOrganizationIndexRoute: typeof AuthSignInTasksChooseOrganizationIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthCreateOrgIndexRoute: AuthCreateOrgIndexRoute,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
  AuthSignInTasksChooseOrganizationIndexRoute:
    AuthSignInTasksChooseOrganizationIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DashboardCatalogProductsProductIdRouteChildren {
  DashboardCatalogProductsProductIdVariantsNewRoute: typeof DashboardCatalogProductsProductIdVariantsNewRoute
}

const DashboardCatalogProductsProductIdRouteChildren: DashboardCatalogProductsProductIdRouteChildren =
  {
    DashboardCatalogProductsProductIdVariantsNewRoute:
      DashboardCatalogProductsProductIdVariantsNewRoute,
  }

const DashboardCatalogProductsProductIdRouteWithChildren =
  DashboardCatalogProductsProductIdRoute._addFileChildren(
    DashboardCatalogProductsProductIdRouteChildren,
  )

interface DashboardRouteRouteChildren {
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardInventoryReceiveRoute: typeof DashboardInventoryReceiveRoute
  DashboardCatalogIndexRoute: typeof DashboardCatalogIndexRoute
  DashboardCatalogProductsProductIdRoute: typeof DashboardCatalogProductsProductIdRouteWithChildren
  DashboardCatalogProductsNewRoute: typeof DashboardCatalogProductsNewRoute
  DashboardCatalogProductsIndexRoute: typeof DashboardCatalogProductsIndexRoute
  DashboardInventoryVariantsVariantIdStockRoute: typeof DashboardInventoryVariantsVariantIdStockRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardInventoryReceiveRoute: DashboardInventoryReceiveRoute,
  DashboardCatalogIndexRoute: DashboardCatalogIndexRoute,
  DashboardCatalogProductsProductIdRoute:
    DashboardCatalogProductsProductIdRouteWithChildren,
  DashboardCatalogProductsNewRoute: DashboardCatalogProductsNewRoute,
  DashboardCatalogProductsIndexRoute: DashboardCatalogProductsIndexRoute,
  DashboardInventoryVariantsVariantIdStockRoute:
    DashboardInventoryVariantsVariantIdStockRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
